// <auto-generated />
using System;
using ConsoleLocaVeiculos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ConsoleLocaVeiculos.Context;

#nullable disable

namespace ConsoleLocaVeiculos.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240415001438_locaveiculos")]
    partial class LocaVeiculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleLocaVeiculos.Program+Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("EhNovoCliente")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantLocados")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ConsoleLocaVeiculos.Program+Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataComeco")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("QuantoTempo")
                        .HasColumnType("int");

                    b.Property<bool>("VaiEstender")
                        .HasColumnType("bit");

                    b.Property<int>("ValorTotal")
                        .HasColumnType("int");

                    b.Property<int?>("VeiculoIDVeiculo")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("VeiculoIDVeiculo");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("ConsoleLocaVeiculos.Program+Veiculo", b =>
                {
                    b.Property<int>("IDVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDVeiculo"));

                    b.Property<DateTime?>("AnoVeiculo")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarcaVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeloVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacaoVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCombustivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDVeiculo");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("ConsoleLocaVeiculos.Program+Reserva", b =>
                {
                    b.HasOne("ConsoleLocaVeiculos.Program+Cliente", null)
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("ConsoleLocaVeiculos.Program+Veiculo", null)
                        .WithMany("Reservas")
                        .HasForeignKey("VeiculoIDVeiculo");
                });

            modelBuilder.Entity("ConsoleLocaVeiculos.Program+Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ConsoleLocaVeiculos.Program+Veiculo", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
